export const DefaultCurrencies = {
  AUD: { symbol: 'A$', name: 'Australian Dollar', position: 'before' },
  BGN: { symbol: 'лв', name: 'Bulgarian Lev', position: 'after' },
  BRL: { symbol: 'R$', name: 'Brazilian Real', position: 'before' },
  CAD: { symbol: 'C$', name: 'Canadian Dollar', position: 'before' },
  CHF: { symbol: 'Fr', name: 'Swiss Franc', position: 'before' },
  CNY: { symbol: '¥', name: 'Chinese Yuan', position: 'before' },
  CZK: { symbol: 'Kč', name: 'Czech Republic Koruna', position: 'after' },
  DKK: { symbol: 'kr', name: 'Danish Krone', position: 'after' },
  EUR: { symbol: '€', name: 'Euro', position: 'before' },
  GBP: { symbol: '£', name: 'British Pound', position: 'before' },
  HKD: { symbol: 'HK$', name: 'Hong Kong Dollar', position: 'before' },
  HUF: { symbol: 'Ft', name: 'Hungarian Forint', position: 'after' },
  IDR: { symbol: 'Rp', name: 'Indonesian Rupiah', position: 'before' },
  ILS: { symbol: '₪', name: 'Israeli New Sheqel', position: 'before' },
  INR: { symbol: '₹', name: 'Indian Rupee', position: 'before' },
  ISK: { symbol: 'kr', name: 'Icelandic Króna', position: 'after' },
  JPY: { symbol: '¥', name: 'Japanese Yen', position: 'before' },
  KRW: { symbol: '₩', name: 'South Korean Won', position: 'before' },
  MXN: { symbol: 'Mex$', name: 'Mexican Peso', position: 'before' },
  MYR: { symbol: 'RM', name: 'Malaysian Ringgit', position: 'before' },
  NOK: { symbol: 'kr', name: 'Norwegian Krone', position: 'after' },
  NZD: { symbol: 'NZ$', name: 'New Zealand Dollar', position: 'before' },
  PHP: { symbol: '₱', name: 'Philippine Peso', position: 'before' },
  PLN: { symbol: 'zł', name: 'Polish Zloty', position: 'after' },
  RON: { symbol: 'lei', name: 'Romanian Leu', position: 'after' },
  RUB: { symbol: '₽', name: 'Russian Ruble', position: 'after' },
  SEK: { symbol: 'kr', name: 'Swedish Krona', position: 'after' },
  SGD: { symbol: 'S$', name: 'Singapore Dollar', position: 'before' },
  THB: { symbol: '฿', name: 'Thai Baht', position: 'before' },
  TRY: { symbol: '₺', name: 'Turkish Lira', position: 'before' },
  UAH: { symbol: '₴', name: 'Ukrainian Hryvnia', position: 'before' },
  USD: { symbol: '$', name: 'US Dollar', position: 'before' },
  ZAR: { symbol: 'R', name: 'South African Rand', position: 'before' },
  COP: { symbol: 'Col$', name: 'Colombian Peso', position: 'before'}
};
